// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PokemonDraft.Data;

#nullable disable

namespace PokemonDraft.Migrations
{
    [DbContext(typeof(DraftDbContext))]
    [Migration("20260603000100_AddMatchupReplayUrl")]
    partial class AddMatchupReplayUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");
#pragma warning restore 612, 618
        }
    }
}
